adding the 2023 base files to this repo

diff --git a/scripts/DEMO/10-misc b/scripts/DEMO/10-misc
--- a/scripts/DEMO/10-misc
+++ b/scripts/DEMO/10-misc
@@ -1,14 +1,39 @@
 #! /bin/bash
 
-# (c) Thomas Lange, 2001-2007, lange@debian.org
+# (c) Thomas Lange, 2001-2017, lange@debian.org
+
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
 ifclass XORG && {
     fcopy -M /etc/X11/xorg.conf
-#    [ -n "$VIDEODRIVER" ] || VIDEODRIVER=vesa
-#    grep -q %%VIDEODRIVER%% $target/etc/X11/xorg.conf &&
-#    perl -pi.orig -pe "s/%%VIDEODRIVER%%/$VIDEODRIVER/" $target/etc/X11/xorg.conf
 }
 
-# add a demo user account
-$ROOTCMD adduser --disabled-login --gecos "fai demo user" demo
-echo "demo:$ROOTPW" | $ROOTCMD chpasswd --encrypted
+if ifclass UBUNTU; then
+     groups="adm cdrom sudo dip plugdev lpadmin sambashare"
+     $ROOTCMD addgroup --system lpadmin || true
+     $ROOTCMD addgroup --system sambashare || true
+fi
+
+# add additional user account
+if [ -n "$username" ]; then
+    if ! $ROOTCMD getent passwd $username ; then
+	$ROOTCMD adduser --disabled-password --gecos "$username user" $username
+	$ROOTCMD usermod -p "$USERPW" $username
+	userdir=$($ROOTCMD getent passwd "$username" | cut -d: -f6 )
+
+	# disable xfce question about default or empty panel
+	if [ -f $target/etc/xdg/xfce4/panel/default.xml ]; then
+	    xfdir=$userdir/.config/xfce4/xfconf/xfce-perchannel-xml
+	    if [ ! -d $target/$xfdir ]; then
+		$ROOTCMD mkdir -p $xfdir
+		$ROOTCMD cp /etc/xdg/xfce4/panel/default.xml $xfdir/xfce4-panel.xml
+		# group name is the same as user name
+		$ROOTCMD chown -R $username:$username $userdir/.config
+	    fi
+	fi
+
+	for g in $groups; do
+	    $ROOTCMD adduser $username $g
+	done
+    fi
+fi
diff --git a/scripts/FAIBASE/10-misc b/scripts/FAIBASE/10-misc
--- a/scripts/FAIBASE/10-misc
+++ b/scripts/FAIBASE/10-misc
@@ -1,32 +1,37 @@
 #! /bin/bash
 
-# (c) Thomas Lange, 2001-2008, lange@debian.org
+# (c) Thomas Lange, 2001-2012, lange@debian.org
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
-# a list of modules which are loaded at boot time
-fcopy -i /etc/modules
-for module in $MODULESLIST; do
-    ainsl -a $target/etc/modules "^$module$"
-done
-
-fcopy /etc/hostname || echo $HOSTNAME     > $target/etc/hostname
 echo $TIMEZONE    > $target/etc/timezone
-ln -fs /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
+if [ -L $target/etc/localtime ]; then
+    fai-link /etc/localtime /usr/share/zoneinfo/${TIMEZONE}
+else
+    cp -f /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
+fi
 
+if [ -f $target/etc/hosts.orig ]; then
+    mv $target/etc/hosts.orig $target/etc/hosts
+fi
+if [ -n "$IPADDR" ]; then
+    ifclass DHCPC || ainsl -s /etc/hosts "$IPADDR $HOSTNAME.$DOMAIN $HOSTNAME"
+else
+    ifclass DHCPC && ainsl -s /etc/hosts "127.0.0.1 $HOSTNAME"
+fi
 fcopy -iM /etc/hosts /etc/motd
 
-# set root password
-echo "root:$ROOTPW" | $ROOTCMD chpasswd --encrypted
 # make /root accessible only by root
-chmod 0700 $target/root
-chown root:root $target/root
+chmod -c 0700 $target/root
+chown -c root:root $target/root
 # copy default dotfiles for root account
 fcopy -ir /root
 
-# create keyboard layout table
-$ROOTCMD bash -c "echo 'console-data console-data/keymap/full select $KEYMAP' | debconf-set-selections"
-$ROOTCMD install-keymap $KEYMAP || true
-# dumpkeys | gzip -9f >$target/etc/console/boottime.kmap.gz
+# use tmpfs for /tmp if not defined in disk_config
+if ! grep -Pq '\s/tmp\s' $target/etc/fstab; then
+    ainsl /etc/fstab "tmpfs     /tmp tmpfs     nodev,nosuid,size=50%,mode=1777   0    0"
+fi
+chmod -c 1777 ${target}/tmp
+chown -c 0:0  ${target}/tmp
 
 exit $error
